id: PA0429D32
initial_creation_type: input
source_metadata:
  Title: Svayambhu Purāṇa
  Editor: '-'
  Publisher: Nagarjuna Institute of Exact Methods
  Place of Publication: Nepal
  Year: '2001'
  Prathama adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīya adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tṛtīya adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturtha adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Pañcama adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣaṣṭhama adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptama adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aṣṭama adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Navama adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Daśama adhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:55:40.022562'
last_modified_at: '2022-03-08T15:55:40.022576'
